# Generated by Django 5.2.7 on 2025-10-07 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='hero_image',
            field=models.ImageField(blank=True, help_text='Recommended size: 1920x1080px (16:9 aspect ratio)', null=True, upload_to='courses/hero_images/'),
        ),
    ]
