# Generated by Django 5.2.7 on 2025-10-07 14:34

import courses.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_hero_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='booking',
            name='email',
            field=models.EmailField(help_text='Valid email address', max_length=254, validators=[courses.models.validate_no_html]),
        ),
        migrations.AlterField(
            model_name='booking',
            name='full_name',
            field=models.CharField(help_text='Full name (2-100 characters, letters only)', max_length=100, validators=[django.core.validators.MinLengthValidator(2, 'Name must be at least 2 characters long.'), django.core.validators.RegexValidator(message='Name can only contain letters, spaces, hyphens, periods, and apostrophes.', regex="^[A-Za-z\\s\\-\\.\\']+$"), courses.models.validate_no_html]),
        ),
        migrations.AlterField(
            model_name='booking',
            name='message',
            field=models.TextField(blank=True, help_text='Optional message (maximum 1000 characters)', max_length=1000, validators=[courses.models.validate_no_html]),
        ),
        migrations.AlterField(
            model_name='booking',
            name='phone',
            field=models.CharField(blank=True, help_text='Optional phone number', max_length=20, validators=[django.core.validators.RegexValidator(message='Phone number can only contain numbers, spaces, +, -, (, and ).', regex='^[0-9\\s\\+\\-\\(\\)]*$'), courses.models.validate_no_html]),
        ),
    ]
